# Generated by Django 4.2.7 on 2025-10-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_app", "0009_userreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="car_name",
            field=models.CharField(
                blank=True, help_text="License number", max_length=100, null=True
            ),
        ),
    ]
