# Generated by Django 4.2.7 on 2025-10-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_app", "0010_userprofile_car_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="car_name",
            field=models.CharField(
                blank=True,
                help_text="Driver's license number",
                max_length=50,
                null=True,
            ),
        ),
    ]
