# Generated by Django 4.2.7 on 2025-10-26 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parking_app", "0011_alter_userprofile_car_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("login", "Login"), ("logout", "Logout")],
                        max_length=10,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile App"),
                            ("admin", "Admin Dashboard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "action"], name="parking_app_user_id_3d269c_idx"
                    ),
                    models.Index(
                        fields=["platform", "timestamp"],
                        name="parking_app_platfor_10bfb1_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="parking_app_timesta_5c4dd9_idx"
                    ),
                ],
            },
        ),
    ]
